stages:
  - build
  - deploy

variables:
  BUILD_NAME: NyxTester
  UNITY_VERSION: "2018.4.36f1"
  BUILD_TARGET: StandaloneWindows64

build:
  stage: build
  tags:
    - unity
  script:     
    - D:\Softs\Unitys\%UNITY_VERSION%\Editor\Unity.exe -logfile D:\Gitlab_runner\Logs\%BUILD_TARGET%.log -customBuildTarget %BUILD_TARGET% -pipelineId %CI_PIPELINE_ID% -batchmode -nographics -executeMethod Nyx.Builder.BuildDefaultProject -quit

  variables:
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: recursive
  artifacts:
    name: "%CI_BUILD_REF_NAME%_%CI_BUILD_REF%"
    expire_in: 1 week
    paths:
      - "Build/*"
    when: on_success

deployItch:
  stage: deploy
  tags:
    - unity
  script: 
    - deployItch.bat
  only:
    - main
